import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import "tailwindcss";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/Footer";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={inter.variable}
    >
      <body className="min-h-full flex flex-col" cz-shortcut-listen="true">
        <Header />
        {children}
        <Toaster />
        <Footer />

      </body>
    </html>
  );
}
